### ISSUE TITLE
What does it mean by dual wieldable?

### ISSUE THREAD

**Issue by JamJarofDoom** [python-bear/tead-1.20.1#1]
Does the mod require another mod like better combat for the dual wieldable feature to work or am i just doing it wrong. I put a sickle in both my off-hand and hand and it dont see a difference.

**Comment by python-bear** [comment]
Na you don't need any other mods for it to work like better combat. So the dual wedding only works if you have a dual wield able weapon in each hand (like sickles or daggers). But I haven't figured out how to make it show the animation when you miss an enemy, it only shows that attack animation when you actually hit a target, but I'll look back into making it easier to understand. Thanks for the tip, and if you have any other questions feel free to ask.

I'm still working on the mod so it's not all done yet.

— P̲ythonBear 🐍🐻

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by python-bear** [comment]
I added the animation when you miss and you attack with an item in your offhand that has dual wielding.
