### ISSUE TITLE
Using shotgun crashes the server (Fabric 1.20.1, Local server)

### ISSUE THREAD

**Issue by Dumpling00** [python-bear/tead-1.20.1#3]
Not sure what else to do/say, but it's consistent. Put bullet in offhand, try to shoot with the shotgun, server crashes, bullet isn't even fired. Doesn't matter if you're OP or player

is there any way that this can be looked into?

Thanks for your time.

**Comment by python-bear** [comment]
Thanks mate. Development has been slow recently and it's my first mod, so it's got a few cracks. There was this thing that I didn't know I had to do in the code when I released the previous version which can lead to some of my mod features crashing into he server. I'll look into it soon, but does it come up with some sort of error message? Thats would be a real help for me.

Thanks for the help.

— P̲ythonBear 🐍🐻

Sent from Proton Mail Android

-------- Original Message --------

**Comment by python-bear** [comment]
I removed the shotgun because it no longer fit the theme of the mod, a new release will be available within a few weeks...

**Comment by Dumpling00** [comment]
Thank you! And no worries.

**Comment by python-bear** [comment]
Sorry for the late reply though. :(

**Comment by Dumpling00** [comment]
It's all good! Life gets busy.

I really enjoyed Tead, I think the strongest mechanic is the Handle, Fabric and the pebbles coming out of cobblestone and other materials.

I initially also loved the new weapons, but I'm sad to say that the RPG Series pack has swooped in with Wizards, Paladins, Rogues and Archers, which makes a lot of tools and armor redundant if both mods are used in tandem.

I was wondering if you'd be interested in developing a lite version with just some of the stuff available? I'd love to help with balancing and making the mod even better from a conceptual standpoint if that's something you're at all willing to explore.

**Comment by python-bear** [comment]
Yeah I'd love to develop a lite version, or to add a config to the normal version so people can pick and choose what they want to enable. It'd be great to get some feedback and balancing help too. I'll be away from my computer for the next three weeks so I wont be able to work on it, but the latest alpha release of the mod is on modrinth and curseforge. It still needs some balancing, bug fixes, and doesn't work with multilayer yet but it should be a vast improvement from when you last played. If you've got some time between now and when I'll be able to add more features id really appreciate you taking a look! Thanks.

— P̲ythonBear 🐍🐻

Sent from Proton Mail Android

-------- Original Message --------
