### ISSUE TITLE
Wrong Crafting

### ISSUE THREAD

**Issue by ual1n** [python-bear/tead-1.20.1#5]
**Game Version:** 1.20.4

**Fabric Loader Version:** 1.16.9

**Problem Description**
The crown crafting recipe in the mod is identical to that of a minecraft, so it is not possible to make the item. There may be other items with a similar problem, so I will report if I find any more.

![2024-11-22_02 44 11](https://github.com/user-attachments/assets/b04ccbfe-6cd7-459d-8bc1-fb65ddd6d290)

**Comment by ual1n** [comment]
Carpet crafting also has conflicts when using two white wools to create a Fabric.

The mod is also incompatible with the [Sword Blocking Mechanics](https://modrinth.com/mod/sword-blocking-mechanics) mod

The mod is also causing crashes when using certain items like the Shotgun.

**Comment by python-bear** [comment]
Thanks bro, I've removed the double wool fabric recipe, changed the crown to use two nuggets instead of ingots for the top two, removed the shotgun, and I'll look to the compatibility issue later.
